# 统计函数

In [4]:
import numpy as np

In [5]:
np.random.seed(2)
arr = np.random.randint(1,20,8)
print(arr)
print(np.sum(arr)) #求和
print(np.mean(arr)) #平均值
print(np.median(arr)) #中位数

[ 9 16 14  9 12 19 12  9]
100
12.5
12.0


In [6]:
#标准差 方差
print(np.var([1,2,3]))
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [ ]:
print(np.max(arr))
print(np.min(arr))
print(np.percentile(arr,20))
print(np.cumsum(arr))  #累积和

19
9
9.0
[  9  25  39  48  60  79  91 100]


# 比较函数

In [ ]:
print(np.greater([1,2,3],2))
print(np.less([1,2,3],2))
print(np.equal([1,2,3],2))
print(np.logical_and(1,0))
print(np.logical_or(1,0))

[False False  True]
[ True False False]
[False  True False]
False


In [18]:
print(np.any([1,0]))
print(np.all([1,1]))

True
True


In [19]:
# 自定义条件
print(np.where(arr>10,arr,0))

[ 0 16 14  0 12 19 12  0]


In [27]:
print(arr)
print(np.select([arr>10,arr<10],[10,5],default=1))

[ 9 16 14  9 12 19 12  9]
[ 5 10 10  5 10 10 10  5]


# 排序函数

In [32]:
np.random.seed(1)
arr = np.random.randint(1,100,15)
print(arr)
print(np.sort(arr))

[38 13 73 10 76  6 80 65 17  2 77 72  7 26 51]
[ 2  6  7 10 13 17 26 38 51 65 72 73 76 77 80]


In [40]:
print(np.unique(arr)) # 去重
arr1 = np.array([1,2])
arr2 = np.array([1,2])
print(np.concatenate((arr1,arr2))) #拼接
print(np.split(arr,3))# 等分
print(np.reshape(arr,[3,5]))

[ 2  6  7 10 13 17 26 38 51 65 72 73 76 77 80]
[1 2 1 2]
[array([38, 13, 73, 10, 76], dtype=int32), array([ 6, 80, 65, 17,  2], dtype=int32), array([77, 72,  7, 26, 51], dtype=int32)]
[[38 13 73 10 76]
 [ 6 80 65 17  2]
 [77 72  7 26 51]]
