# numpy中的常用函数
## 基本数学函数

In [2]:
import numpy as np

In [6]:
#平方根
arr = np.array([1,2,3])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081]


In [9]:
#e的指数
print(np.exp(1))

2.718281828459045


In [12]:
#自然对数   lnX
print(np.log(2.718))

0.999896315728952


In [16]:
#sin cos
print(np.sin(np.pi))
print(np.cos(np.pi))
print(np.tan(np.pi/2))

1.2246467991473532e-16
-1.0
1.633123935319537e+16


In [17]:
#绝对值
print(np.abs(-1))

1


In [18]:
#幂
print(np.power(2,3))

8


In [20]:
#银行家四舍五入
print(np.round([4.5,5.4]))

[4. 5.]


In [21]:
#向上取整  向下取整
arr = np.array([1.6,25.1,1.1])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26.  2.]
[ 1. 25.  1.]


In [24]:
#检测缺失值NaN
np.isnan(np.nan)

np.True_