# ndarray
## ndarray特性
### 多维性

In [2]:
import numpy as np

In [ ]:
arr = np.array(5) #0维
print(arr)
print('维度',arr.ndim) #打印维度

5
0


In [6]:
arr = np.array([1,2,3]) #1维
print(arr)
print('维度',arr.ndim) #打印维度

[1 2 3]
维度 1


In [20]:
arr = np.array([[1,2,3],[4,5,6]]) #2维
print(arr)
print('维度',arr.ndim) #打印维度

[[1 2 3]
 [4 5 6]]
维度 2


### 同质性

In [11]:
arr = np.array([1,'hello'])  #不同的数据类型会自动转换
print(arr)

['1' 'hello']


In [13]:
arr = np.array([1,2.5])  #不同的数据类型会自动转换
print(arr)
print(arr.dtype)

[1.  2.5]
float64


## ndarray属性

In [29]:
arr = np.array(1)
print(arr)
print('数组形状',arr.shape)
print('元素个数',arr.size)
print(arr.dtype)
print('元素转置',arr.T)

1
数组形状 ()
元素个数 1
int64
元素转置 1


In [30]:
arr = np.array([1,2,3])
print(arr)
print('数组形状',arr.shape)
print('元素个数',arr.size)
print(arr.dtype)
print('元素转置',arr.T)

[1 2 3]
数组形状 (3,)
元素个数 3
int64
元素转置 [1 2 3]


In [31]:
arr = np.array([[1,2.5,3],[3,4,5]])
print(arr)
print('数组形状',arr.shape)
print('元素个数',arr.size)
print(arr.dtype)
print('元素转置',arr.T)

[[1.  2.5 3. ]
 [3.  4.  5. ]]
数组形状 (2, 3)
元素个数 6
float64
元素转置 [[1.  3. ]
 [2.5 4. ]
 [3.  5. ]]


## ndarray的创建

In [35]:
# 基础创建方法
list1 = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr)

[4. 5. 6.]


In [37]:
# copy方法
arr1 = np.copy(arr) #只是元素相同
print(arr1)
arr1[0] = 2
print(arr)

[4. 5. 6.]
[4. 5. 6.]


In [43]:
# 预定义形状
# 全0 全1 未初始化 固定值

#全0
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

arr1 = np.zeros((4,))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[0. 0. 0. 0.]


In [45]:
# 全1
arr = np.ones((2,3),dtype = np.int64)
print(arr)

[[1 1 1]
 [1 1 1]]


In [50]:
# 未定义
arr = np.empty((4,3))
print(arr)

[[1.10209208e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 1.42413554e-306 2.46567317e+179]
 [5.88732607e-091 4.27629916e-033 4.31993725e-038]
 [1.37037791e-071 3.99910963e+252 1.46236216e+185]]


In [53]:
# 固定值
arr = np.full((3,3),2026,dtype=float)
print(arr)
arr1 = np.zeros_like(arr)
print(arr1)

[[2026. 2026. 2026.]
 [2026. 2026. 2026.]
 [2026. 2026. 2026.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
#  等差数列
arr = np.arange(2,10,2)  #起始，终止（不包含），步长
print(arr)

[2 4 6 8]


In [ ]:
# 等间隔数列
arr = np.linspace(0,10,5) #起始，终止，个数
print(arr)
arr1 = np. arange(0,11,2.5)
print(arr1)

[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]


In [78]:
# 对数间隔数列
arr = np.logspace(0,4,3,base = 2)
print(arr)

[ 1.  4. 16.]


In [82]:
#单位矩阵
arr = np.eye(4,3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]]


In [83]:
# 对角矩阵
arr = np. diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [92]:
# 随机数组生产
# 生成0-1之间的随机浮点数（均匀）
arr = np.random.rand(2,3)
print(arr)
# 指定范围之间
arr1 = np.random.uniform(3,6,(2,3))
print(arr1)

#整数
arr2 = np.random.randint(3,100,(2,3))
print(arr2)

[[0.39972224 0.28170609 0.33003484]
 [0.60073906 0.31525911 0.81040259]]
[[5.94845868 4.88701424 5.27748005]
 [4.87082672 3.36847239 5.66385939]]
[[32 26 40]
 [26 72 40]]


In [ ]:
# 生产随机数列（正态分布）（-3到3）
#两边概率小，中间概率大
arr = np.random.randn(2,3)
print(arr)

[[-0.43785311 -0.86742719 -1.25936157]
 [-0.41571153  0.74031063  1.98949884]]


In [104]:
#种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
