# ndarray算术运算

In [1]:
#
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a ** 2)

[5 7 9]
[1 4 9]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a * b)
print(a + 3)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 广播机制 把形状为 1 的那一维「扩展」出去
a = np.array([1,2,3]) 
b = np.array([[1],[2],[3]])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
