# ndarray数据类型
布尔 bool
整数 int unit
浮点 float
复数 complex


In [2]:
import numpy as np

In [ ]:
arr = np.array([1,0,2,0],dtype=np.bool)
print(arr)

[ True False  True False]


In [5]:
arr = np.array([1,0,2,0],dtype=np.int64)
print(arr)

[1 0 2 0]


# 索引和切片

In [ ]:
# 一维数组
np.random.seed(1)
arr = np.random.randint(1,100,30)
print(arr)
print(arr[0])
print(arr[:]) #all
print(arr[2:5]) #左包右不包

[38 13 73 10 76  6 80 65 17  2 77 72  7 26 51 21 19 85 12 29 30 15 51 69
 88 88 95 97 87 14]
38
[38 13 73 10 76  6 80 65 17  2 77 72  7 26 51 21 19 85 12 29 30 15 51 69
 88 88 95 97 87 14]
[73 10 76]
[ True  True  True False  True False  True  True  True False  True  True
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]


In [ ]:
print(arr[(arr>10)&(arr<50)])

[38 13 17 26 21 19 12 29 30 15 14]


In [19]:
#slice切片
print(arr[slice(2,15,3)])

[73  6 17 72 51]


In [32]:
# 二维数组
np.random.seed(1)
arr = np.random.randint(1,100,(3,3))
print(arr)
print(arr[1][1])
print(arr[1,1:3])
print(arr[arr>50])
print(arr[2][arr[2]>50])
print(arr[:,2])

[[38 13 73]
 [10 76  6]
 [80 65 17]]
76
[76  6]
[73 76 80 65]
[80 65]
[73  6 17]
